#ifndef ILogManager_h
#define ILogManager_h
//
//  Copyright (c) 2017 Microsoft. All rights reserved.
//

#import "ILogger.h"
#import "ILogController.h"
#import "EnumCommon.h"

#import <Foundation/Foundation.h>

#define EVTILogManager EVTILogManagerV1

/*!
 @brief EVTILogManagerV1
*/
@protocol EVTILogManagerV1 <NSObject>

/*!
 @brief Retrieves an instance of the ILogger for logging telemetry events.
 @param apiKey A string that contains the API key.
 @return An ILogger pointer that points to the Logger for the specified API Key.
 */
- (nullable id<EVTILogger>)loggerForApiKey:(nonnull NSString *)apiKey;

/*!
 @brief Retrieves an instance of the ILogController.
 @return An ILogController that can be used to control how events are sent.
 */
- (nullable id<EVTILogController>)logController;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value A string that contains the property value.
 */
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name stringValue:(nonnull NSString *)value;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name stringValue:(nonnull NSString *)value kind:(enum EVTPropertyValueKind)piiKind;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name boolValue:(BOOL)value;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name dateValue:(nonnull NSDate *)value;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name doubleValue:(double)value;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name longValue:(int64_t)value;
- (enum EVTStatus)setContextWithName:(nonnull NSString *)name UUIDValue:(nonnull NSUUID *)value;

/*!
 @brief Retrieves an EVTISemanticContext instance
 that you can use to specify context information&mdash;such as device, operating system, hardware, or user information.
 @details Context information applies to all logger instances except ones that are overwritten by individual logger instances.
 */
- (nullable id<EVTISemanticContext>)semanticContext;

@end

#endif // ILogManager_h

