//
//  Copyright (c) 2017 Microsoft. All rights reserved.
//  version: 0.2.2.1
//

#ifndef EVENTSDK_EVTLogManager_h
#define EVENTSDK_EVTLogManager_h

#import "ILogConfiguration.h"
#import "ISemanticContext.h"
#import "ILogger.h"

/*!
 @brief The EVTLogManager static class manages the telemetry lgging system.
*/
@interface EVTLogManager : NSObject

/*!
 @brief Starts the telemetry logging system with the default configuration.
 @return A status.
 */
+ (enum EVTStatus)start;

/*!
 @brief Starts the telemetry logging system with a custom configuration.
 @return A status.
 */
+ (enum EVTStatus)startWithConfiguration:(nonnull id<EVTILogConfiguration>)config;

/*!
 @brief Tears down the telemetry logging system.
 */
+ (enum EVTStatus)teardown;

/*!
 @brief Gets the ILogger interface of a Logger instance given a API key.
 @param apiKey A string that contains the API key.
 @return An ILogger pointer that points to the Logger for the specified API key.
 */
+ (nullable id<EVTILogger>)loggerForApiKey:(nonnull NSString *)apiKey;

/*!
 @brief Attempts to send any pending telemetry events that are currently cached either in memory, or on disk.
 @return A status.
 */
+ (enum EVTStatus)uploadNow;

/*!
 @brief Pauses the transmission of telemetry events to the data collector.
 @details While paused, events continue to be queued on the client side&mdash;cached either in memory or on disk.
 @return A status.
 */
+ (enum EVTStatus)pauseTransmission;

/*!
 @brief Resumes the transmission of telemetry events to the data collector.
 @return A status.
 */
+ (enum EVTStatus)resumeTransmission;

/*!
 @brief Sets the transmit profile for event transmission, given the name of a transmit profile.
 @details A transmit profile is a collection of hardware and system settings (like network connectivity, power state, etc.)
 that determines how efficiently telemetry events are transmitted.
 @param profileName A string that contains the name of the transmit profile you want to set.
 @return A status.
 */
+ (enum EVTStatus)setTransmitProfile:(nonnull NSString *)profileName;

/*!
 @brief Loads the transmit profiles specified in JSON.
 @param profilesJSON A string that contains the JSON that contains the transmit profiles.
 @return A status.
 */
+ (enum EVTStatus)loadTransmitProfiles:(nonnull NSString *)profilesJSON;

/*!
 @brief Resets the transmit profiles to contain only default profiles.
 @return A status.
 */
+ (enum EVTStatus)resetTransmitProfiles;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value A string that contains the property value.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name stringValue:(nonnull NSString *)value;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system, and tags it with its PII kind.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value A string that contains the value of the property.
 @param piiKind The kind of personal identifiable information (PII), as one of the ::EVTPropertyValueKind enumeration values.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name stringValue:(nonnull NSString *)value kind:(enum EVTPropertyValueKind)piiKind;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value A boolean that contains the value of the property.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name boolValue:(BOOL)value;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value An NSDate object that contains the property value.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name dateValue:(nonnull NSDate *)value;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value A double that contains the property value.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name doubleValue:(double)value;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name An string that contains the name of the property.
 @param value An int64_t that contains the property value.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name longValue:(int64_t)value;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param value An NSUUID object that contains the property value.
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name UUIDValue:(nonnull NSUUID *)value;

/*!
 @brief Retrieves an EVTISemanticContext instance
 that you can use to specify context information&mdash;such as device, operating system, hardware, or user information.
 @details Context information applies to all logger instances except ones that are overwritten by individual logger instances.
 */
+ (nonnull id<EVTISemanticContext>)semanticContext;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param stringArrayValue An array of NSString
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name stringArrayValue:(nonnull NSArray *)stringArrayValue;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param boolArrayValue An array of BOOL
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name boolArrayValue:(nonnull NSArray *)boolArrayValue;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param dateArrayValue An array of NSDate
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name dateArrayValue:(nonnull NSArray *)dateArrayValue;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param longArrayValue An array of NSNumber
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name longArrayValue:(nonnull NSArray *)longArrayValue;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param doubleArrayValue An array of NSNumber
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name doubleArrayValue:(nonnull NSArray *)doubleArrayValue;

/*!
 @brief Adds (or overrides) a property of the context for the telemetry logging system.
 @details Context information applies to events generated by all ILogger instances&mdash;unless it is overwritten on a particular ILogger instance.
 @param name A string that contains the name of the property.
 @param uuidArrayValue An array of NSUUID
 */
+ (enum EVTStatus)setContextWithName:(nonnull NSString *)name UUIDArrayValue:(nonnull NSArray *)uuidArrayValue;

@end

#endif // EVENTSDK_EVTLogManager_h

